name: ci-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test of these containers
        container: ["ubuntu-dev", "alpine-dev"]
    timeout-minutes: 90
    container:
      image: ghcr.io/${{ github.actor }}/${{ matrix.container }}:latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache build deps
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: |
          ~/.ccache
          ${{github.workspace}}/build/_deps
        key: ${{ runner.os }}-deps-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-deps-
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja \
             -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - name: Build & Test
      run: |
          cd ${{github.workspace}}/build
          cat /proc/cpuinfo
          ninja base/all io/all strings/all util/all
          GLOG_logtostderr=1 gdb -batch -ex "run" -ex "thread apply all bt" \
             ./accept_server_test || true
          GLOG_logtostderr=1 ctest -V -L CI
          # ./proactor_test --gtest_filter=*Migrate --logtostderr --vmodule=proactor=2,uring_fiber_algo=1



