name: docker release

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
# ===============================================================
#   Building Dev Images
# ===============================================================
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    -
      name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
          platforms: arm64,amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build echo_server ubuntu
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        build-args: |
          QEMU_CPU='max,pauth-impdef=on'
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/${{ github.actor }}/echo_server:latest
        file: tools/docker/Dockerfile.ubuntu-prod